name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ── Job déploiement : Ansible ────────────────────────────────
  deploy:
    needs: build-and-push   # attend que les images soient pushées
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ANSIBLE_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventories/setup.yml inventories/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
